# Reference: https://cloud.google.com/appengine/docs/flexible/python/reference/app-yaml

runtime: python
env: flex
entrypoint: gunicorn -t 300 -b :$PORT -w 3 wsgi:app
service: feed-form-app
service_account: feedformservice@technical-solutions-237213.iam.gserviceaccount.com

runtime_config:
  python_version: 3.7

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
