FROM python:3.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1 

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN apt-get update 
RUN apt-get install ffmpeg libsm6 libxext6 -y
CMD gunicorn -t 360 -b :8080 -k gevent -w 3 main:app